In [1]:
import numpy as np

In [2]:
#1 D array
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#  boolean value 
b=np.ones((3,3) , dtype=bool)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [17]:
# Reshaping arrays
array=np.array([1,2,3,4,5,6])
newArray= array.reshape(2,3)
print(newArray)

[[1 2 3]
 [4 5 6]]


In [27]:
# Two arrays stached vertically and use of np dot and np sum
c=np.array([1,2,3,4]).reshape(2,2)
d=np.array([5,6,7,8]).reshape(2,2)
print(c)
print(d)
e=np.dot(c,d)
print(e)
f=np.sum(e,axis=0)

print(f)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[62 72]
