In [1]:
import numpy as np

In [2]:
arr= np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Extract all odd numbers
arr[0::2]

array([1, 3, 5, 7, 9])

In [6]:
# Replace all odd numbers with -1
arr[0::2]= -1

In [7]:
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
# Creating a pattern
a=np.array([1,2,3])
b=np.repeat(a,3)
print(b)
c=np.tile(a,3)
print(c)
d=np.concatenate((b,c))
print(d)

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [28]:
#Removing repeating items and taking a sum of numbers between 5 and 10
e=np.array([1,2,3,4,5])
f=np.array([4,5,6,7,8,9])
g=f[2:6]
print(g)
h=np.sum(g)
print(h)

[6 7 8 9]
30
